name: Deploy

env:
    EB_PACKAGE_S3_BUCKET_NAME : "test-bucket-for-eb-goq"
    EB_APPLICATION_NAME : "Eb-test"
    EB_ENVIRONMENT_NAME : "Eb-test-env"
    DEPLOY_PACKAGE : "test-app${{ github.sha }}.zip"
    AWS-REGION_NAME : "us-east-1"

on:
    push:
        branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v4.1.6
      - name: Create zip deployment package
        run: |
          zip -r ${{ env.DEPLOY_PACKAGE }} ./ -x "*.git*"
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS-REGION_NAME }}
      - name: Copy deployment package to S3 bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/

  cd_pipeline:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS-REGION_NAME }}
      - name: Create EB Application
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ${{ env.EB_APPLICATION_NAME }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          version_label: ${{ github.sha }}
          region: ${{ env.AWS-REGION_NAME }}
          deployment_package: ${{ env.DEPLOY_PACKAGE }}
