name: "PIPELINE: Prod AWS EB Deploy"

env:
    EB_PACKAGE_S3_BUCKET_NAME : "test-goq-test-bucket"
    EB_APPLICATION_NAME : "qog-test-flask"
    EB_ENVIRONMENT_NAME : "Qog-test-flask-env-1"
    DEPLOY_PACKAGE : "test-app${{ github.sha }}.zip"
    AWS-REGION_NAME : "us-east-1"

on:
    push:
        branches: [ main ]

jobs:
  deploy:
    uses: ./.github/workflows/t-deploy.yml