name: "TEMPLATE: Dependency Audit"

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  dependency-audit:
    name: Dependency audit
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with: 
          python-version: ${{ inputs.python-version }}
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Audit all dependencies
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: requirements.txt
          summary: true
