name: Dev Code Review 

on: 
  push:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/t-Build.yml
    with:
      python-version: 3.11
      os: ubuntu-latest

  lint:
    needs: [build]
    uses: ./.github/workflows/t-lint.yml
    with:
      python-version: 3.11
      os: ubuntu-latest

  unit-test:
    needs: [lint]
    uses: ./.github/workflows/t-unit-test.yml
    with:
      python-version: 3.11
      os: ubuntu-latest

  security-code-review:
    needs: [unit-test]
    uses: ./.github/workflows/t-security_code_review.yml
    with:
      python-version: 3.11
      os: ubuntu-latest
  
  # codeql:
  #   needs: [security-code-review]
  #   uses: ./.github/workflows/t-codeql.yml
  #   with:
  #     python-version: 3.11
  #     os: ubuntu-latest
  
  dependency-audit:
    needs: [security-code-review]
    uses: ./.github/workflows/t-dependency_audit.yml
    with:
      python-version: 3.11
      os: ubuntu-latest

  external-link-validation:
    needs: [dependency-audit]
    uses: ./.github/workflows/t-external-link-validation.yml
    with:
      python-version: 3.11
      os: ubuntu-latest
